name: Semantic Release

on:
  workflow_call:
    inputs:
      DRY_RUN:
        type: boolean
        default: false
        required: false

    secrets:
      GH_TOKEN:
        required: true

jobs:
  semantic-release:
    runs-on: ubuntu-latest
    steps:
      - name: Set Up Composer Authentication
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
        if: env.GH_TOKEN != ''
        run: composer config --global --auth github-oauth.github.com $GH_TOKEN
        shell: bash

      - name: Setup Environment
        uses: SP-Applications/actions/.github/actions/setup-environment@main
        with:
          FETCH_DEPTH: 0
          SETUP_NODE: true
          INSTALL_DEPENDENCIES: true
          INSTALL_DEV_DEPENDENCIES: true

      - name: Run Semantic Release
        run: npx semantic-release --dry-run=${{ inputs.DRY_RUN }}
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
